### ISSUE TITLE
Legge til et docker build context path til action.yml

### ISSUE THREAD

**Issue by PrebenFUNBIT** [Funbit-AS/gha-deploy-wagtail-ec2#5]
Denne kan default være dette men må også kunne ta inn context for at vi kan sette annen path feks "." for å si på root

```
    - name: Build and push to Amazon ECR
      uses: docker/build-push-action@v3
      with:
        context: wagtail/${{ inputs.project-name }} 
        file: wagtail/${{ inputs.project-name }}/docker/${{ inputs.image-name }}/Dockerfile
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.project-name }}-${{ inputs.image-name }}:${{ inputs.deployment-target }}
        push: true
        cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ inputs.project-name }}-${{ inputs.image-name }}:${{ inputs.deployment-target }}
        cache-to: type=inline
```
